services:
  postgres:
    platform: linux/amd64
    image: nilgil183/pg_search_ko:1.0
    environment:
      - 'POSTGRES_DB=book'
      - 'POSTGRES_USER=nilgil'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - '5432:5432'
