server.servlet.context-path: /api

spring:
  application.name: book-search
  profiles.active: local
  web.resources.add-mappings: false
  sql.init.mode: never

---
spring.config.activate.on-profile: local

spring:
  docker.compose.lifecycle-management: start_only
  sql.init.mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/book
    username: nilgil
    password: secret

logging:
  level:
    org.springframework.jdbc.core: DEBUG
