server.servlet.context-path: /api

spring:
  application.name: book-search
  profiles.active: local
  web.resources.add-mappings: false
  sql.init.mode: never

---
spring.config.activate.on-profile: local

spring:
  docker.compose.lifecycle-management: start_only
  datasource:
    url: jdbc:postgresql://localhost:5432/book
    username: nilgil
    password: secret
  sql.init:
    mode: always
    schema-locations: classpath:schema.sql, classpath:search.sql
logging:
  level:
    org.springframework.jdbc.core: DEBUG

---
spring.config.activate.on-profile: local-dev

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/book
    username: nilgil
    password: secret
  sql.init:
    mode: always
    schema-locations: classpath:schema.sql, classpath:search.sql
